readableTimeString: Exclude the last unreadable NULL char
eclipse-4diac/4diac-forte pull request #107
Opened 2024-05-04 07:30 UTC by kumajaya

I found this bug with directed stdout/stderr to file. Notepad++ shown excess of NULL

2024-05-07 08:55 UTC, MartinMelikMerkumians requested changes

2024-05-07 08:55 UTC, MartinMelikMerkumians commented on src/arch/readableTimeString.cpp
>    dt.toString(str.data(), str.size());
Perhaps I am wrong, but as I read this https://cplusplus.com/reference/string/string/data/ you shouldn't write on data in the first place

I propose to change the code to
```
char dateCString[sizeof("DT#1970-01-01-00:00:00.000")];
func_NOW().toString(dateCString, sizeof(dateCString));
std::string dateString(dateCString, sizeof(dateCString));
return dateString;
```

2024-05-07 08:57 UTC, MartinMelikMerkumians commented on src/arch/readableTimeString.cpp
>    dt.toString(str.data(), str.size());
In a follow up step, the fixed toString buffer sizes, accessed by getToStringBufferSize should be put into a template, similar to numeric_limits or added as a constexpr static class variable, so that it can be used in constexpr use cases like here.
FYI @azoitl

2024-05-07 11:58 UTC, kumajaya commented on src/arch/readableTimeString.cpp
>    dt.toString(str.data(), str.size());
> Perhaps I am wrong, but as I read this https://cplusplus.com/reference/string/string/data/ you shouldn't write on data in the first place
> 
> I propose to change the code to
> 
> ```
> char dateCString[sizeof("DT#1970-01-01-00:00:00.000")];
> func_NOW().toString(dateCString, sizeof(dateCString));
> std::string dateString(dateCString, sizeof(dateCString));
> return dateString;
> ```

How about if I write it:
```
  CIEC_DATE_AND_TIME dt = func_NOW();
  size_t length = dt.getToStringBufferSize() - 1;
  std::vector<char> str(length);
  dt.toString(str.data(), length);
  return std::string(str.data(), length);
```
or:
```
  CIEC_DATE_AND_TIME dt = func_NOW();
  size_t length = dt.getToStringBufferSize() - 1;
  std::vector<char> str(length);
  dt.toString(&str[0], length);
  return std::string(&str[0], length);
```

2024-05-08 14:23 UTC, kumajaya commented
Change getRealtimeString() to getRealtimeString().c_string() in devlog.cpp will remove the excess '\0' but in my opinion the source of problem from here.

2024-05-08 15:21 UTC, MartinMelikMerkumians commented on src/arch/readableTimeString.cpp
>    dt.toString(str.data(), str.size());
Thanks for the link, you are right, my resource was outdated it seems, so your original version is fine

2024-05-08 18:16 UTC, MartinMelikMerkumians approved these changes

2024-05-08 21:25 UTC, azoitl approved these changes

2024-05-08 21:26 UTC, merged