Add test to ctf tracer and helper classses
eclipse-4diac/4diac-forte pull request #114
Opened 2024-05-25 06:09 UTC by cochicde

This PR is to have a base for testing the ctf traces. It has classes representing all possible events being traced, a way of reading the trace files, and a minimal example of comparison of a small FB network.

The test is very simple, but the rest is what's needed for further improvement of the trace module and for more complex analysis of traces.

2024-05-27 18:03 UTC, mx990 requested changes

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.h
> +  EventMessage(const std::string& paEventType, std::unique_ptr<AbstractPayload> paPayload, int64_t paTimestamp);
I would suggest passing the string parameters by value instead of by reference. For an explanation why this is generally preferred, please refer to https://xania.org/202101/cpp-by-value-args.

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.h
> +  bool specificPayloadEqual(const AbstractPayload& other) const;
I believe those methods should be marked `override` (same in the other concrete payload classes)?

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.cpp
> +}
I would suggest moving this rather trivial implementation into the header file (same for the similar constructors in the other classes and `operator==`s).

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.h
> +  virtual bool operator==(const AbstractPayload& other) const;
Why is this `operator==` marked as virtual?

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.cpp
> +    std::abort();
Please log an error message instead of just calling `abort()` to help diagnose test failures.

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.cpp
> +  auto const instanceNameField = bt_field_structure_borrow_member_field_by_name_const(field, "instanceName");
Please check the return values to make sure the fields exist and have the correct class.

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.cpp
> +      bt_field_structure_borrow_member_field_by_name_const(field, "eventId"));
Please make sure the field exists and has the correct class.

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.cpp
> +      bt_field_structure_borrow_member_field_by_name_const(field, "value"));
Please make sure the fields exist and have the correct class.

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.cpp
> +  }
Why is adding extra backslashes necessary here? What if there is already a `STRING` with an IEC 61131-3 escape `$'`?

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.cpp
> +    auto arrayField = bt_field_structure_borrow_member_field_by_name_const(field, fieldNames[fieldRunner]);
Please make sure the field exists and has the correct class.

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.cpp
> +  }
Instead of using two arrays and a for loop for reading the fields, I would suggest to extract this into a separate method, which is passed the field, name, and destination pointer (e.g., `readField(field, "inputs", &mInputs)`).

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.h
> +  EventMessage(const bt_message* message);
Please stick to the coding guidelines for parameter names (e.g., `paMessage`).

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/TraceReaderSink.cpp
> +// ************************** //
I believe those functions should each be declared as `static` and put inside an `extern "C" { ... }` block.

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.h
> +  AbstractPayload(const bt_field* field);
Please add a default virtual destructor to this class.

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/ctfTracerTest.cpp
> +std::vector<EventMessage> getEventMessages(const std::string& path){
Please consider separating this generic support functionality from the concrete test above.

2024-05-27 18:03 UTC, mx990 commented on tests/core/trace/EventMessage.cpp
> +  return mEventType == other.mEventType  && *mPayload == *other.mPayload;
Please check `mPayload` for `nullptr` (since you also have a check in `getPayloadString` above).

2024-05-29 17:00 UTC, cochicde commented on tests/core/trace/EventMessage.h
> +  EventMessage(const std::string& paEventType, std::unique_ptr<AbstractPayload> paPayload, int64_t paTimestamp);
nice one! done

2024-05-29 17:00 UTC, cochicde commented on tests/core/trace/EventMessage.h
> +  bool specificPayloadEqual(const AbstractPayload& other) const;
yes! done

2024-05-29 17:01 UTC, cochicde commented on tests/core/trace/EventMessage.cpp
> +}
I'm particularly a fan of fully separating the definition from the declaration, mainly to have the header file easier to read in case I don't need information from the implementation. I'd keep as it is, at least for now

2024-05-29 17:02 UTC, cochicde commented on tests/core/trace/EventMessage.h
> +  virtual bool operator==(const AbstractPayload& other) const;
wrong copy+paste from somewhere. fixed

2024-05-29 17:02 UTC, cochicde commented on tests/core/trace/EventMessage.cpp
> +    std::abort();
added info before every `abort`

2024-05-29 17:02 UTC, cochicde commented on tests/core/trace/EventMessage.cpp
> +  auto const instanceNameField = bt_field_structure_borrow_member_field_by_name_const(field, "instanceName");
right! added everywhere (I think)

2024-05-29 17:13 UTC, cochicde commented on tests/core/trace/EventMessage.cpp
> +  }
I added the string representation actually mainly for debugging purposses, to make sure I was reading the the ctf messages from the files exactly as the `babeltrace2` command does and quickly check with `diff`. `babeltrace2` prints the strings and adds the escape character. That's the only reason to have it also here.

2024-05-29 17:13 UTC, cochicde commented on tests/core/trace/EventMessage.cpp
> +  }
good one. much nicer now

2024-05-29 17:13 UTC, cochicde commented on tests/core/trace/EventMessage.h
> +  EventMessage(const bt_message* message);
done

2024-05-29 17:14 UTC, cochicde commented on tests/core/trace/TraceReaderSink.cpp
> +// ************************** //
I added the static but the macros down in the file just take the function pointers and do the magic to offer the plugin and components, and no `extern C` is needed, as I quickly saw, the function pointers are stored, but the function name itself is not used from the outside

2024-05-29 17:14 UTC, cochicde commented on tests/core/trace/EventMessage.h
> +  AbstractPayload(const bt_field* field);
added

2024-05-29 17:15 UTC, cochicde commented on tests/core/trace/ctfTracerTest.cpp
> +std::vector<EventMessage> getEventMessages(const std::string& path){
done

2024-05-29 17:15 UTC, cochicde commented on tests/core/trace/EventMessage.cpp
> +  return mEventType == other.mEventType  && *mPayload == *other.mPayload;
right!

2024-05-29 18:43 UTC, mx990 commented on tests/core/trace/TraceReaderSink.cpp
> +// ************************** //
Some compilers also have different *calling conventions* for C and C++ functions, besides the name mangling issue, see https://en.cppreference.com/w/cpp/language/language_linkage and also https://stackoverflow.com/questions/2594178/why-do-you-need-extern-c-for-c-callbacks-to-c-functions for the concrete case of passing a callback defined in C++ to a C function.

2024-05-29 19:43 UTC, cochicde commented on tests/core/trace/TraceReaderSink.cpp
> +// ************************** //
interesting! I'll add _calling convetions_ in C callbacks to the things that will break my code when I least expect it. Updated!

2024-05-29 19:57 UTC, mx990 approved these changes

2024-05-30 05:25 UTC, merged