Update forte_Init.cpp
eclipse-4diac/4diac-forte pull request #153
Opened 2024-06-08 13:19 UTC by franz-hoepfinger-4diac

error: 'ipPort' was not declared in this scope; did you mean 'pIpPort'?

2024-06-08 16:37 UTC, cochicde commented
@franz-hoepfinger-4diac  I'm currently cleaning up all the duplicated `init` and `main` files across different architectures here https://github.com/eclipse-4diac/4diac-forte/pull/151

Its should be ready now, but I don't have a freeRTOS setup to test it. Can you check  if #151 works?

2024-08-16 11:28 UTC, mx990 approved these changes

2024-08-16 13:29 UTC, ernstblechaPT approved these changes

2024-09-05 14:00 UTC, MartinMelikMerkumians requested changes

2024-09-05 14:00 UTC, MartinMelikMerkumians commented on src/arch/freeRTOS/forte_Init.cpp
> +    if(!instance->startupNewDevice(pIpPort)) {
according to the coding guidelines, type prefixes like `p` are obsolete and shall not be used anymore.
Please fix this by renaming the variable to `ipPort` in lines 81, 82 and 84

2024-09-23 06:28 UTC, azoitl commented
This PR is superseded by @cochicde's clean-up in Pr #151.

2024-09-23 06:28 UTC, closed without merging