First version of a CVS reader block
eclipse-4diac/4diac-forte pull request #223
Opened 2024-09-05 13:31 UTC by azoitl

2024-09-05 13:55 UTC, MartinMelikMerkumians requested changes

2024-09-05 13:55 UTC, MartinMelikMerkumians commented on src/modules/utils/GEN_CSV_READER_fbt.cpp
> +    mCSVFile.open(FILE_NAME().getStorage().c_str());
you are calling c_str() several times. I would suggest to store the result of the first call and use it later, as FILE_NAME will probably not modified in this function anymore

2024-09-05 13:55 UTC, MartinMelikMerkumians commented on src/modules/utils/GEN_CSV_READER_fbt.cpp
> +        std::size_t newPos = line.find(';', oldPos);
seeing this, you implicitly assume a German-language CSV file, correct?
English-language (and several others) CSVs use the comma ',' as the separator.
In the current version the use of the CSV Reader is limited to German-language (or others using the semicolon as separator) CSVs. I would suggest to extract the separator to an additional input for the FB, enhancing usability of the FB

2024-09-08 04:56 UTC, diplfranzhoepfinger commented
GOOD ! 

as said, i would like to make a INI-File Reader-Writer Block.

2026-05-31 18:56 UTC, azoitl commented
I don't think I find time in the near future to turn this into something better usable.

2026-05-31 18:56 UTC, closed without merging