Add storage module integration with INI file handling. Include options to enable OPC UA with CMake and implement functions for loading and storing data from settings.ini by section and key.
eclipse-4diac/4diac-forte pull request #232
Opened 2024-09-17 20:50 UTC by franz-hoepfinger-4diac

Add storage module integration with INI file handling. Include options to enable INI with CMake and implement functions for loading and storing data from settings.ini by section and key.

- Added CMakeLists.txt for storage module integration.
- Added CMakeLists.txt for INI handling within the storage module.
- Implemented functions in INI_fbt.cpp to load and store data from settings.ini by section and key.

2024-09-17 20:51 UTC, franz-hoepfinger-4diac commented
https://github.com/eclipse-4diac/4diac-ide/pull/485

2024-09-19 15:37 UTC, azoitl requested changes
Can you please clean the commit message and the comments. I don't see any OPC UA in your commit!

2024-09-19 15:44 UTC, diplfranzhoepfinger commented
> Can you please clean the commit message and the comments. I don't see any OPC UA in your commit!

i do ....

2024-09-19 15:48 UTC, franz-hoepfinger-4diac commented
cleaned it up ...

2024-09-19 17:09 UTC, azoitl commented
I don't think it makes sense to have this in the official 4diac FORTE repo. It introduces an undocumented hidden dependency to your code.  This strongly violates the Eclipse development process. I think it makes more sense that you  build up your own repo where you put that kind of stuff together and use it for your builds via an external module.

2024-09-20 06:40 UTC, franz-hoepfinger-4diac reviewed
Changes done.

2024-09-20 06:41 UTC, franz-hoepfinger-4diac commented
> It introduces an undocumented hidden dependency to your code. 

OK. sorry for that. 
i need to learn how to make it right. 
and it is not my Code, it is from other People, but its MIT. 

> This strongly violates the Eclipse development process.

yes, sorry, i need step by step learn it.

2024-09-20 15:00 UTC, azoitl commented
The Eclipse development process has a very clear position on third party content. It needs to be clearly marked and also reproted. You can see all third party dependency Eclipse 4diac has in our project pages. For that we need to report them and get them veted and approved. We normally don't accept just a github repo as third party dependency. It has to be certain releases, because between releases licenses may change.

2024-09-21 07:15 UTC, diplfranzhoepfinger commented
yes, must learn this !

2025-09-15 20:54 UTC, azoitl commented
I think this kind of functionality should for now be provided in separate libraries. With the new lib infrastructure from eclipse 4diac it is rather easy to provide own libs.

2025-09-15 20:54 UTC, closed without merging

2026-04-25 02:12 UTC, diplfranzhoepfinger commented
Main Problem solved: 

https://github.com/brofield/simpleini/pull/95

we removed the very very old UTF8 Lib.