Wago updates
eclipse-4diac/4diac-forte pull request #238
Opened 2024-09-21 21:24 UTC by moniwe

2024-09-22 20:19 UTC, azoitl requested changes

2024-09-22 20:19 UTC, azoitl commented on src/modules/wagokbus/modular/wagoHandle.cpp
> +//  paState = static_cast<TForteWord>((static_cast<TForteWord>(inDataWord[1]) << 8) + (static_cast<TForteWord>(inDataWord[0])));
please remove commented code.

2024-09-23 05:53 UTC, cochicde reviewed
Looks good! amazing!

2024-09-23 06:18 UTC, azoitl commented
Can you please correct the copy right headers of the generated files and update the copyright headers of the changed files.

2024-09-28 18:41 UTC, azoitl approved these changes

2024-09-28 18:41 UTC, merged