Abstract tracer and create an internal one for test purposes
eclipse-4diac/4diac-forte pull request #267
Opened 2024-10-29 18:36 UTC by cochicde

This PR is part a branch with some other things, so some things are still not used here. 
The folllowing was done here:
- Abstract tracer: any mention of the `barectf` tracer was removed from the main code and hidden in `BarectfPlatformFORTE`. To do that, a `CForteTracer` typedef was created which can be set to other tracers during compilation time. `BarectfPlatformFORTE` (and others tracers) have methods such as `traceInstanceData`, `traceReceiveInputEvent`, etc. which mirror the ones from `barectf`. The Function Blocks then call these methods in  `CForteTracer` class. 
- Internal tracer: Is a tracer that instead of tracing into a file, it traces into a vector of `EventMessage` which contains the same information as the `barectf` traces. This is only compile if the tracer tests are enabled.
- Flexible Tracer: A shell over both `BarectfPlatformFORTE` and the internal tracer, which allows selecting one or the other during runtime. This is the default tracer if tracer tests are enabled.
- Babeltrace2 Message Factory: everything related to `babeltrace2` was moved out of the `EventMessages` and this factory allows creating `EventMessages` from the `bt_field` (and other) types defined by `babeltrace2`. 

The main idea of this new code is to be able generate traces using `barectf` but also directly into memory and be able to have the same class to compare them (`EventMessage`)

2024-10-30 09:43 UTC, diplfranzhoepfinger commented
we have a Tracer ? 
@azoitl 
this would be VERY helpful. 
such a Thing which X/Y Coordinates and writing Diagramms of Variables ? 
I am Impressed !

2024-10-30 20:32 UTC, azoitl commented
> we have a Tracer ? @azoitl this would be VERY helpful. such a Thing which X/Y Coordinates and writing Diagramms of Variables ? I am Impressed !

I don't think this is what you can to with that. Currently tracing is more for getting deeper insights on what is going on. But it heavily impacts performance and is not suitable for non-linux platforms.

2024-10-30 20:37 UTC, diplfranzhoepfinger commented
ahhhhhhhhhhhhhhhh .... 

so this would be a totally different thing: 
having a Chart Draw module in IDE, to make Plots during a Watch ?

2024-10-30 20:52 UTC, mx990 requested changes

2024-10-30 20:52 UTC, mx990 commented on src/core/trace/flexibleTracer.h
> +class CFlexibelTracer final {
```suggestion
class CFlexibleTracer final {
```

2024-10-30 20:53 UTC, azoitl commented
> ahhhhhhhhhhhhhhhh ....
> 
> so this would be a totally different thing: having a Chart Draw module in IDE, to make Plots during a Watch ?

yes

2024-10-31 17:29 UTC, cochicde commented on src/core/trace/flexibleTracer.h
> +class CFlexibelTracer final {
are you sure? 
https://www.merriam-webster.com/dictionary/flexibel?utm_campaign=sd&utm_medium=serp&utm_source=jsonld

2024-10-31 19:04 UTC, mx990 commented on src/core/trace/flexibleTracer.h
> +class CFlexibelTracer final {
Yes, when I click the link you posted, I get:
> The word you've entered isn't in the dictionary.

It even suggests the correct spelling: https://www.merriam-webster.com/dictionary/flexible

2024-11-01 11:54 UTC, cochicde commented on src/core/trace/flexibleTracer.h
> +class CFlexibelTracer final {
Apparently I was very tired

2024-11-01 12:43 UTC, mx990 approved these changes

2024-11-02 09:17 UTC, merged