Implement startup behavior for EInit events
eclipse-4diac/4diac-forte pull request #298
Opened 2024-12-24 14:53 UTC by MandKastner

Unconnected event pins with the event type EInit of FBs will be triggered automatically during startup

2024-12-24 19:14 UTC, mx990 requested changes
I am somewhat troubled that we are adding a separate memory allocation to hold the input event connection counters for *all* FB instances. In case of the similar monitoring counters, users can at least disable monitoring on constrained devices or if it is simply not needed.

I would like to propose several alternative approaches for discussion:
1. we use a common counter for all `EInit` events [^1],
2. we use a mark-and-sweep search when the resource is started, marking all FBs with input connections on `EInit` events [^1] and then triggering all unmarked FBs (also resetting the mark),
3. we only allocate the counters when `SFBInterfaceSpec::mEITypeNames` is not `nullptr`, which would at least reduce the impact for most FBs [^2].

In any case, we may want to add a compile-time flag to disable automatic triggering of unconnected `EInit` events on startup, including any potential overhead incurred thereof.

[^1]: This would slightly change the semantics if we had multiple `EInit` events, but maybe we should disallow that anyway?
[^2]: In that case, we should probably also make sure that FB types in the source tree with only `EEvent` events have `mEITypeNames` set to `nullptr`.

2024-12-24 19:14 UTC, mx990 commented on src/core/funcbloc.cpp
> +  mInputEventConnectionCount = std::make_unique<size_t[]>(getFBInterfaceSpec().mNumEIs);
I believe you need to re-create the array when there interface is reconfigured, see callers of `setupEventMonitoringData()`.

2024-12-24 19:14 UTC, mx990 commented on src/core/funcbloc.h
> +    [[nodiscard]] bool isConnected(TEventID paEIID) const {
Please rename this to `isInputEventConnected`.

2024-12-24 19:14 UTC, mx990 commented on src/core/funcbloc.cpp
> +        triggerEInitEvents();
It seems this will also trigger `EInit` events after a reconfiguration or warm restart? Is this the desired behavior?

2025-01-09 11:40 UTC, MandKastner commented
@mx990 Thank you for your suggestions. I would prefer to keep the infrastructure to check if a event port is connected and go with your 3rd suggestion to reduce allocated memory. As you also suggested i moved the trigger mechanism to a SIFB and perform the recursive search there, this will allow users to decide about the triggering process.

2025-01-09 11:44 UTC, MandKastner commented on src/core/funcbloc.cpp
> +  mInputEventConnectionCount = std::make_unique<size_t[]>(getFBInterfaceSpec().mNumEIs);
I am not sure if i understand what you mean. The only caller of `setupMonitoringData()` is `initialize()`. In my understanding the existing `unique_ptr` will give up its ownership and take the new one with the second call of `initialize()` . With the release the managed memory should be freed and the new array created.

2025-01-09 12:06 UTC, mx990 commented on src/core/funcbloc.cpp
> +  mInputEventConnectionCount = std::make_unique<size_t[]>(getFBInterfaceSpec().mNumEIs);
It is also called in https://github.com/eclipse-4diac/4diac-forte/blob/1511891ea208ff88fd4e3db1bc093f12f0e5ab91/src/core/genfb.tpp#L221 after setting up the interface of a generic FB.

2025-01-09 12:54 UTC, azoitl commented on src/core/funcbloc.cpp
> +  mInputEventConnectionCount = std::make_unique<size_t[]>(getFBInterfaceSpec().mNumEIs);
But with @MandKastner current implementation using a std::unique_ptr this does not really matter. Or do I miss something?

2025-01-09 12:54 UTC, azoitl commented on src/core/funcbloc.cpp
> +  mInputEventConnectionCount = std::make_unique<size_t[]>(getFBInterfaceSpec().mNumEIs);
Ah I missed the point. Yes we need to put a call there as well.

2025-01-17 11:02 UTC, franz-hoepfinger-4diac commented
I will test this now. 
eagerly waiting for this.

2025-01-17 13:56 UTC, franz-hoepfinger-4diac commented
so, First Test: Failed: 
it seems none of the EInit Pins are triggered: 

![image](https://github.com/user-attachments/assets/0d071734-030e-43ac-acc0-08590c861e83)

2025-01-17 13:56 UTC, franz-hoepfinger-4diac commented
ahhhhhhhhhhh i see... there is a new FB: E_TRIG!

2025-01-17 14:00 UTC, franz-hoepfinger-4diac commented
Working now ... Cool. 

![image](https://github.com/user-attachments/assets/abf0eedb-12ee-4954-93ff-2f57a69781bc)

2025-01-17 16:21 UTC, franz-hoepfinger-4diac commented
on bigger PRojects i get a lot of 
`ERROR: T#25000000000: External event queue is full, external event dropped!`
Messages.

2025-01-17 16:30 UTC, azoitl requested changes

2025-01-17 16:30 UTC, azoitl commented on src/core/funcbloc.cpp
> +void CFunctionBlock::triggerEventsOfType(TEventTypeID paEventTypeId) {
please move to E_TRIG FB

2025-01-17 16:30 UTC, azoitl commented on src/core/funcbloc.cpp
> +        getResource()->getResourceEventExecution()->startEventChain(CConnectionPoint(this, eventId));
use the eventchain execution thread which was used to triggere the R_TRIG fb and add the events to the internal event list.

2025-01-17 16:30 UTC, azoitl commented on src/stdfblib/events/E_TRIG_fbt.cpp
> +void FORTE_E_TRIG::triggerEvents(forte::core::CFBContainer* paContainer, TEventTypeID paEventType) {
paContainer is not really needed you could call the getResoruce here.

2025-01-17 16:30 UTC, azoitl commented on src/stdfblib/events/E_TRIG_fbt.cpp
> +        triggerEvents(getResource(), eventTypeId);
use the paECET for triggereEvents so that you do not need to use the external events everywhere.

2025-01-17 16:32 UTC, azoitl commented
> on bigger PRojects i get a lot of `ERROR: T#25000000000: External event queue is full, external event dropped!` Messages.

I would expect that, we need more memory to handle that. But with my comments from above you only need to make the internal event queue larger

2025-01-17 19:18 UTC, franz-hoepfinger-4diac commented
> > on bigger PRojects i get a lot of `ERROR: T#25000000000: External event queue is full, external event dropped!` Messages.
> 
> I would expect that, we need more memory to handle that. But with my comments from above you only need to make the internal event queue larger

Understand. 
yes, waiting for this Improvement. 
but still a big step forward.

2025-01-23 06:56 UTC, franz-hoepfinger-4diac commented
> > on bigger PRojects i get a lot of `ERROR: T#25000000000: External event queue is full, external event dropped!` Messages.
> 
> I would expect that, we need more memory to handle that. But with my comments from above you only need to make the internal event queue larger

you are true. 

using a Project with 2416 Blocks after putting 
`-DFORTE_EventChainExternalEventListSize=512`

i get 
`ERROR: T#2000000000: Event queue is full, event dropped!`


so it seems we need to increase both Queues now. 

later the External one will be unaffected right ? 
@MandKastner --> great work so far. 
@azoitl --> good reviewer .

2025-01-27 07:12 UTC, MandKastner commented
@franz-hoepfinger-4diac thank you for testing thats really helpful.


> 
> later the External one will be unaffected right ? @MandKastner --> great work so far. @azoitl --> good reviewer .
> 

Yes, i think the external event queue should not be affected anymore. I believe that you just have to increase the size of the internal one.

2025-01-27 09:23 UTC, mx990 requested changes

2025-01-27 09:23 UTC, mx990 commented on src/core/funcbloc.cpp
> +  }
Can we move the surrounding if and `getFBInterfaceSpec().mNumEIs` argument into `setupInputConnectionTrackingData()?

2025-01-27 09:23 UTC, mx990 commented on src/core/funcbloc.h
> +    }
I would suggest making `setupInputConnectionTrackingData()` protected.

2025-01-27 20:15 UTC, azoitl reviewed
appart from @mx990 comments everything else looks good.

2025-01-27 20:15 UTC, azoitl commented on src/core/funcbloc.h
> +    }
yes it should definitly not be public.

2025-01-29 14:29 UTC, mx990 requested changes

2025-01-29 14:29 UTC, mx990 commented on src/core/funcbloc.h
> +    }
Please also move the `getFBInterfaceSpec().mNumEIs` argument into `setupInputConnectionTrackingData()`:
```suggestion
    void setupInputConnectionTrackingData() {
      if (getFBInterfaceSpec().mEITypeNames != nullptr) {
        mInputEventConnectionCount = std::make_unique<size_t[]>(getFBInterfaceSpec().mNumEIs);
      }
    }
```
or is there a reason why we would pass different values here?

2025-01-31 11:03 UTC, MandKastner commented on src/core/funcbloc.h
> +    }
you are right there is no reason i missed that, thx

2025-01-31 15:01 UTC, mx990 approved these changes

2025-01-31 16:23 UTC, azoitl approved these changes

2025-01-31 16:24 UTC, merged