add F_ANY_AS_STRING
eclipse-4diac/4diac-forte pull request #58
Opened 2024-03-21 21:32 UTC by moniwe

2024-03-22 09:44 UTC, MartinMelikMerkumians commented
@moniwe could you please add tests for your function? Thanks in advance

2024-03-22 09:44 UTC, MartinMelikMerkumians requested changes
Code looks good, but please add some tests. Thanks in advance

2024-03-30 11:37 UTC, MartinMelikMerkumians approved these changes

2024-03-30 14:51 UTC, azoitl approved these changes

2024-03-30 14:52 UTC, merged