Add a Reset to Timer FBs
eclipse-4diac/4diac-forte pull request #97
Opened 2024-04-23 10:41 UTC by franz-hoepfinger-4diac

solves https://github.com/eclipse-4diac/4diac-ide/pull/79

2024-05-24 17:09 UTC, diplfranzhoepfinger commented
@azoitl any help needed ? 

eclipse-4diac/4diac-ide#79 was merged. Thanks so far.

2024-05-25 18:34 UTC, azoitl commented
> @azoitl any help needed ? 
> 
> [eclipse-4diac/4diac-ide#79](https://github.com/eclipse-4diac/4diac-ide/pull/79) was merged. Thanks so far.

@franz-hoepfinger-4diac oh sorry I thought I already had reviewed and merged it. Will do now.

2024-05-25 18:35 UTC, azoitl approved these changes

2024-05-25 18:44 UTC, azoitl requested changes
I was to fast with my approval. I think there are some issues with this PR.

2024-05-25 18:44 UTC, azoitl commented on src/stdfblib/events/E_TP_fbt.cpp
The reset event and the according event connections are not in this file

2024-05-25 18:44 UTC, azoitl commented on src/stdfblib/events/E_TP_fbt.h
The reset event and the according event connections are not in this file

2024-05-25 18:44 UTC, azoitl commented on src/stdfblib/events/E_PULSE_fbt.h
The reset event and the according event connections are not in this file

2024-05-25 18:44 UTC, azoitl commented on src/stdfblib/events/E_PULSE_fbt.cpp
The reset event and the according event connections are not in this file

2024-05-28 20:31 UTC, franz-hoepfinger-4diac commented
> I was to fast with my approval. I think there are some issues with this PR.

what is missing ? 
it is auto-Generated Code, so it should be 1:1 what the IDE made ... 

i just checked it again, also the `g_nStringIdR` is there.

2024-05-31 15:08 UTC, azoitl commented
I thought compared to the XML file changes more changes should be in the cpp. But as you pointed out they are already there. Sorry.

2024-05-31 15:09 UTC, azoitl approved these changes

2024-05-31 15:09 UTC, merged

2024-05-31 18:18 UTC, diplfranzhoepfinger commented
thanks. !